services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bible-api

    ports:
      - '3000:3000'

    environment:
      NODE_ENV: production
      PORT: 3000

      DATABASE_URL: ${DATABASE_URL}

      REDIS_URL: redis://redis:6379

      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

      BASE_URL: ${BASE_URL}

      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}

      INSTANCE_NAME: nest-1

    depends_on:
      - postgres
      - redis

    restart: unless-stopped

  postgres:
    image: postgres:16

    container_name: bible-postgres

    environment:
      # These variables are loaded from your .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '5433:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7

    container_name: bible-redis

    ports:
      - '6379:6379'

    volumes:
      - redis_data:/data

    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
