// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { BadRequestException } from '@nestjs/common';
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

// const dbUrl = process.env.DATABASE_URL;
const dbUrl = env('DATABASE_URL');

if (!dbUrl) {
  throw new BadRequestException('DATABASE_URL is not defined');
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    // url: process.env['DATABASE_URL'],
    // url: process.env.DATABASE_URL!,
    url: dbUrl,
  },
});
